name: solacc

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

env:
  HATCH_VERBOSE: "2"
  HATCH_VERSION: "1.16.5"

jobs:
  solacc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'

      - name: Install hatch
        run: pip install "hatch==${HATCH_VERSION}"

      - name: Verify linters on solution accelerators
        run: make solacc

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: build/
          if-no-files-found: error
